[env:nologo_esp32c3_super_mini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = nologo_esp32c3_super_mini
framework = arduino

; By default, only 1.25Mb of 4Mb flash is available in the flash partition. As we need more, and we are not using OTA nor SPIFFS,
; we can change to 'huge_app' which will give us ~3MB for our app
board_build.partitions = huge_app.csv

; Velocidad esperada en el puerto por el 'Serial Monitor' (con el ESP32C3 supermini no lo autodetecta)
monitor_speed = 115200
build_flags =
  -I include

  -DLGFX_USE_V1
  -std=gnu++17

  ; Lo siguiente es necesario para que se conecte el 'Serial Monitor'
  ; (asumiendo que se inicializa en el código a la velocidad arriba indicada)
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  ;
  ; ===== OPCIONES =====
  -DTFT_RGB_ORDER=TFT_RGB
  -DTFT_INVERSION_ON=1
  ; ===== RESOLUCIÓN =====
  -DTFT_WIDTH=240
  -DTFT_HEIGHT=320
  ; ===== PINES (los míos) =====
  -DTFT_CS=0
  -DTFT_DC=1
  -DTFT_RST=2
  -DTFT_MOSI=3
  -DTFT_SCLK=4
  ; MISO no usado
  -DTFT_MISO=-1
  ; Backlight (si usamos TFT OLED no tendrá pin BL y se ignorará el control del brillo)
  -DTFT_BL=21
  -DTFT_BACKLIGHT_ON=HIGH

  ; ===== FRECUENCIA SPI =====
  -DSPI_FREQUENCY=80000000
  -DSPI_READ_FREQUENCY=20000000

lib_deps =
  lovyan03/LovyanGFX@^1.2.7
